
import './globals.css';
import './styles.css';
import './output.css';
import HomePage from './pages/home';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Fire Safety & Compliance Experts Brisbane | Firevolt",
  description: "Firevolt provides comprehensive fire safety services including test & tag, emergency planning, fire training, and extinguisher services across Brisbane. Stay compliant with our expert solutions.",
  openGraph: {
    title: "Fire Safety Compliance Services Brisbane | Firevolt",
    description: "Brisbane's trusted fire safety experts offering test & tag, fire warden training, extinguisher services & compliance solutions for businesses.",
    url: "https://www.firevolt.com.au",
    siteName: "Firevolt Fire Safety Experts",
    images: [
      {
        url: "/images/meta/twitter-card.png",
        width: 1200,
        height: 630,
        alt: "Firevolt Fire Safety Services Brisbane",
      },
    ],
    type: "website",
    locale: "en_AU",
  },
  keywords: [
    "fire safety Brisbane",
    "test and tag services QLD",
    "fire warden training",
    "fire extinguisher servicing",
    "compliance services Brisbane",
    "emergency procedures planning",
    "fire equipment training",
    "business fire safety",
    "fire compliance experts",
    "Brisbane fire services",
    "Fire Services Acacia Ridge",
    "Fire Services Albany Creek",
    "Fire Services Albion",
    "Fire Services Archerfield",
    "Fire Services Banyo",
    "Fire Services Boondall",
    "Fire Services Bray Park",
    "Fire Services Brendale",
    "Fire Services Bulimba",
    "Fire Services Bulwer Island",
    "Fire Services Burpengary",
    "Fire Services Burpengary East",
    "Fire Services Caboolture",
    "Fire Services Caboolture South",
    "Fire Services Capalaba",
    "Fire Services Carole Park",
    "Fire Services Chermside",
    "Fire Services Chermside South",
    "Fire Services Chermside West",
    "Fire Services Coopers Plains",
    "Fire Services Coorparoo",
    "Fire Services Darra",
    "Fire Services Deception Bay",
    "Fire Services Doboy",
    "Fire Services Doomben",
    "Fire Services Eagle Farm",
    "Fire Services Geebung",
    "Fire Services Heathwood",
    "Fire Services Hemmant",
    "Fire Services Hendra",
    "Fire Services Hillcrest",
    "Fire Services Kedron",
    "Fire Services Larapinta",
    "Fire Services Lawnton",
    "Fire Services Lindum",
    "Fire Services Lytton",
    "Fire Services Meeandah",
    "Fire Services Morayfield",
    "Fire Services Myrtletown",
    "Fire Services Narangba",
    "Fire Services Newstead",
    "Fire Services North Lakes",
    "Fire Services Northgate",
    "Fire Services Nudgee",
    "Fire Services Nudgee Beach",
    "Fire Services Nundah",
    "Fire Services Parkinson",
    "Fire Services Pinkenba",
    "Fire Services Port of Brisbane",
    "Fire Services Redbank",
    "Fire Services Redbank Plains",
    "Fire Services Richlands",
    "Fire Services Rochedale",
    "Fire Services Rocklea",
    "Fire Services Salisbury",
    "Fire Services Sandstone Point",
    "Fire Services Springfield Central",
    "Fire Services Springfield Lakes",
    "Fire Services Stafford",
    "Fire Services Strathpine",
    "Fire Services Sumner",
    "Fire Services Sunnybank Hills",
    "Fire Services Toombul",
    "Fire Services Virginia",
    "Fire Services Wacol",
    "Fire Services Warner",
    "Fire Services Whinstanes",
    "Fire Services Wynnum Central",
    "Fire Services Wynnum North",
    "Fire Services Yeerongpilly",
    "Fire Services Zillmere",
    
  ],
  authors: [{ name: "Firevolt Team", url: "https://www.firevolt.com.au" }],
  alternates: {
    canonical: "https://www.firevolt.com.au",
  },
  metadataBase: new URL("https://www.firevolt.com.au"),
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  //Get hayden to add google verification code
  // verification: {
  //   google: "Add Google Verification Code",
  // },
  twitter: {
    card: "summary_large_image",
    title: "Fire Safety & Compliance Experts Brisbane | Firevolt",
    description: "Protect your business with Firevolt's comprehensive fire safety services across Brisbane.",
    images: ["/images/meta/twitter-card.png"],
  },
};

const Home = () => {
  return <HomePage/>
}

export default Home;
